import dj_database_url 
"""
Django settings for money_multiplier project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import logging

# Only load .env file in local development, not in production
if os.getenv('ENVIRONMENT') != 'production':
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Setup basic logging for configuration
logging.basicConfig(level=logging.INFO)
config_logger = logging.getLogger('database')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if os.getenv('ENVIRONMENT') == 'local':
    SECRET_KEY = 'django-insecure-1*cjz4-m0lyfmo0@@3jg#m0xdl7ft3srpx(kk7ww6r8s*bb8ef'
else:
    SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1*cjz4-m0lyfmo0@@3jg#m0xdl7ft3srpx(kk7ww6r8s*bb8ef')

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('ENVIRONMENT') == 'local':
    DEBUG = True
else:
    DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

if os.getenv('ENVIRONMENT') == 'local':
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.1.6', '*']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '.onrender.com', 'algotrading-backend.onrender.com', '.railway.app', '.up.railway.app', 'kite-algotrading-production.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'trading',  # Your main app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'money_multiplier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'money_multiplier.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Print environment debug info
config_logger.info(f"ENVIRONMENT = {os.getenv('ENVIRONMENT')}")
config_logger.info(f"DATABASE_URL exists = {bool(os.getenv('DATABASE_URL'))}")
config_logger.info(f"DB_HOST = {os.getenv('DB_HOST')}")

# FORCE PRODUCTION DATABASE for Render.com deployment
# Check if we're on Render.com or if ENVIRONMENT is production
is_render = '.onrender.com' in os.getenv('RENDER_EXTERNAL_URL', '') or os.getenv('RENDER_SERVICE_NAME')
is_production = os.getenv('ENVIRONMENT', '').lower() == 'production'
environment = os.getenv('ENVIRONMENT', '').lower()

config_logger.info(f"is_render = {is_render}")
config_logger.info(f"is_production = {is_production}")
config_logger.info(f"RENDER_EXTERNAL_URL = {os.getenv('RENDER_EXTERNAL_URL')}")

if environment == 'local' and not is_render and not is_production:
    config_logger.info("Using SQLite for local development")
    # Use SQLite for local development
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR.parent / 'db.sqlite3',
    #     }
    # }
    
    # Alternative: If you want to use PostgreSQL locally, uncomment this and comment SQLite above
    config_logger.info("Using local PostgreSQL for development")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'admin@123'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 60,
                # Remove SSL requirement for local development
            },
        }
    }
else:
    config_logger.info("FORCING PostgreSQL for production/Render deployment")
    # Always construct DATABASE_URL for Render.com
    db_host = os.getenv('DB_HOST', 'dpg-d26hggjuibrs739ss0h0-a.oregon-postgres.render.com')
    db_port = os.getenv('DB_PORT', '5432')
    db_name = os.getenv('DB_NAME', 'algotrading_60j3')
    db_user = os.getenv('DB_USER', 'algotrading_user')
    db_password = os.getenv('DB_PASSWORD', 'KaVpfEyKnvm5g4buBl5tuizkvqoNYJ1x')

    # FORCE PostgreSQL for production - override any local settings
    DATABASE_URL = os.getenv('DATABASE_URL')
    if not DATABASE_URL:
        DATABASE_URL = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
        config_logger.info("Constructed DATABASE_URL from individual components")

    config_logger.info("Using hardcoded production credentials for reliability")

    # ALWAYS use hardcoded production database to avoid any configuration issues
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {
                'connect_timeout': 60,
                'sslmode': 'require',
            },
        }
    }
        
    config_logger.info(f"Database HOST = {DATABASES['default']['HOST']}")
    config_logger.info(f"Database NAME = {DATABASES['default']['NAME']}")
    config_logger.info(f"Database USER = {DATABASES['default']['USER']}")
    config_logger.info(f"Database PORT = {DATABASES['default']['PORT']}")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'trading_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'trading.log',
            'formatter': 'detailed',
            'level': 'DEBUG',
        },
        'screener_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'screener.log',
            'formatter': 'detailed',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'trading': {
            'handlers': ['console', 'trading_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'screener': {
            'handlers': ['console', 'screener_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'chartink': {
            'handlers': ['console', 'screener_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'fallback_screener': {
            'handlers': ['console', 'screener_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'database': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'chrome_env': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Ensure logs directory exists
import os
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
if os.getenv('ENVIRONMENT') == 'local':
    # Allow all origins during local development
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Production - be more specific with allowed origins
    CORS_ALLOW_ALL_ORIGINS = False
    
    # Get CORS origins from environment variable or use defaults
    cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',')]
    else:
        CORS_ALLOWED_ORIGINS = [
            "https://algotrading-frontend.onrender.com",
            "https://kite-algotrading-production.up.railway.app",
            "https://algotrading-frontend.up.railway.app",
            "https://algotrading-frontend.railway.app",
        ]

# Local development origins (always included)
CORS_ALLOWED_ORIGINS_LOCAL = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.1.6:5173",
    "http://192.168.1.6:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

# Combine production and local origins
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS.extend(CORS_ALLOWED_ORIGINS_LOCAL)

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
]

# Allow specific methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Preflight request cache time
CORS_PREFLIGHT_MAX_AGE = 86400

# CSRF settings for CORS
CSRF_TRUSTED_ORIGINS = [
    "https://algotrading-frontend.onrender.com",
    "https://kite-algotrading-production.up.railway.app",
    "https://algotrading-frontend.up.railway.app",
    "https://algotrading-frontend.railway.app",
    "http://localhost:3000",
    "http://localhost:5173",
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
