version: '3.8'

services:
  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Django Backend with SQLite
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - sqlite_data:/app/db.sqlite3
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL:-http://localhost:3000}
    ports:
      - "80:80"
    depends_on:
      - backend

  # Nginx Load Balancer (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data:
  redis_data:
