name: algotrading-app
region: nyc

services:
  # Backend Django Service
  - name: backend
    source_dir: /backend
    github:
      repo: akshaychincholkar/act-algotrading
      branch: main
      deploy_on_push: true
    run_command: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health/
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".ondigitalocean.app,algotrading-app-backend.ondigitalocean.app,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://algotrading-app-frontend.ondigitalocean.app,http://localhost:3000,http://localhost:5173"
      - key: REDIS_URL
        value: "${redis.REDIS_URL}"

  # Frontend React Service
  - name: frontend
    source_dir: /frontend
    github:
      repo: akshaychincholkar/act-algotrading
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: "${backend.PUBLIC_URL}"

databases:
  # PostgreSQL Database
  - name: db
    engine: PG
    version: "13"
    size: basic-xs
    num_nodes: 1
    production: false

  # Redis Database
  - name: redis
    engine: REDIS
    version: "6"
    size: basic-xs
    num_nodes: 1
    production: false
