# Generated by Django 5.1.1 on 2025-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('cmp', models.FloatField()),
                ('slp', models.FloatField()),
                ('sl', models.FloatField()),
                ('tgtp', models.FloatField()),
                ('tgt', models.FloatField()),
                ('stb_sl', models.FloatField()),
                ('stb_ipt', models.FloatField()),
                ('stb', models.FloatField()),
                ('sb', models.FloatField(blank=True, null=True)),
                ('rsi', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('candle', models.CharField(blank=True, max_length=20)),
                ('volume', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('invested', models.FloatField()),
                ('pl', models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=6)),
                ('percent_pl', models.FloatField()),
                ('booked', models.FloatField()),
                ('rr', models.FloatField()),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
