# Generated by Django 5.1.1 on 2025-07-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_trade_booked_alter_trade_candle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('broker_id', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trading.user')),
                ('access_token', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.user'),
        ),
    ]
