# Generated by Django 5.1.1 on 2025-07-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_user_authenticator_trade_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalParameters',
            fields=[
                ('key', models.TextField(max_length=250, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
