# Generated by Django 5.1.1 on 2025-07-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_globalparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='broker_id',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='user_shortname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
