# Generated by Django 5.1.1 on 2025-07-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_email_id_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diversification', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ipt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment Per Trade')),
                ('rpt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Risk Per Trade')),
                ('invested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('donation_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_percent_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_percert_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.user')),
            ],
            options={
                'verbose_name': 'User ROI',
                'verbose_name_plural': 'User ROIs',
            },
        ),
    ]
