# Generated by Django 5.1.1 on 2025-07-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_userroi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroi',
            name='id',
        ),
        migrations.AlterField(
            model_name='userroi',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trading.user'),
        ),
    ]
