# Generated by Django 5.1.1 on 2025-07-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_screener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screener',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.user'),
        ),
    ]
