# Generated by Django 5.1.1 on 2025-07-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticator',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='authenticator',
            name='api_key',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='api_secret',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='access_token',
            field=models.TextField(default=None),
        ),
    ]
