# Generated by Django 5.1.1 on 2025-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_remove_authenticator_date_remove_user_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
