# Generated by Django 5.1.1 on 2025-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_alter_authenticator_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticator',
            name='user',
        ),
        migrations.AddField(
            model_name='authenticator',
            name='user_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
