# Generated by Django 5.1.1 on 2025-07-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_remove_authenticator_user_authenticator_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screener',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.user'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.user'),
        ),
        migrations.AlterField(
            model_name='userroi',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trading.user'),
        ),
    ]
